name: Run Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20 # Ensure Node.js 20 is used
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
