name: Run Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install All Dependencies
        run: npm run setup

      - name: Start Application
        run: |
          npm run start &
          sleep 5
          echo "Attempting to start server at http://localhost:8080"

      - name: Wait for Application to Start
        run: |
          n=0
          until [ $n -ge 10 ]
          do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
            if [ $response -eq 200 ]; then
              echo "Server is up and running!"
              break
            fi
            n=$((n+1))
            echo "Waiting for server... attempt $n"
            sleep 10
          done
          if [ $n -ge 10 ]; then
            echo "Server failed to start within expected time."
            exit 1
          fi

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
